CONNECT TO SAMPLE;

DROP TABLE FILM;

DROP TABLE FOOD_BEVERAGES;

DROP TABLE SHOP;

DROP TABLE TICKET;

DROP TABLE SESSIONS;

CREATE TABLE FILM (
  idFILM INTEGER NOT NULL,
  TITLE varchar(45),
  RELEASE_YEAR INTEGER,
  GENRE varchar(45),
  PRIMARY KEY (idFILM)
  );
  
CREATE TABLE FOOD_BEVERAGES (
  idPRODUCT INTEGER NOT NULL,
  Product_Name varchar(45),
  Category_ varchar(45),
  Size_ varchar(45),
  Price decimal(4,2),
  PRIMARY KEY (idPRODUCT)
  );
  
CREATE TABLE SESSIONS (
  idSESSION INTEGER NOT NULL,
  Room INTEGER,
  Time_ time,
  Seat_Capacity INTEGER NOT NULL,
  PRIMARY KEY (idSESSION)
  );
  
CREATE TABLE TICKET (
  idTICKET INTEGER NOT NULL,
  fkSession INTEGER,
  fkFilm INTEGER,
  Price decimal(4,2),
  Date_ DATE,
  Seat INTEGER,
  PRIMARY KEY (idTICKET),
  FOREIGN KEY (fkFilm) REFERENCES film (idFILM),
  FOREIGN KEY (fkSession) REFERENCES SESSIONS (idSESSION)
);

CREATE TABLE SHOP (
  fkProduct INTEGER,
  fkTicket INTEGER,
  FOREIGN KEY (fkProduct) REFERENCES FOOD_BEVERAGES (idPRODUCT),
  FOREIGN KEY (fkTicket) REFERENCES TICKET (idTICKET)
);
